@startuml
skinparam SequenceArrowThickness 2
skinparam DefaultFontSize 18
skinparam ParticipantFontSize 20
skinparam ActorFontSize 20
skinparam NoteFontAlignment center

!pragma teoz true

actor "Usuário" as USER

box "SISP" #LightSkyBlue
    control "Controle de\nSessão" as CTRLS
    participant "Thread\nDetecção" as TDETECT
    participant YOLO
    participant "Motor" as MT
    participant "Thread\nAúdio" as TAUD
end box

USER -> CTRLS : Pressiona\no botão
CTRLS -> TDETECT ++: Inicia sessão  

loop Sessão esta ativa

    TDETECT -> TDETECT : Captura imagem\nusando a câmera

    TDETECT -> YOLO ++: Imagem
    YOLO -> YOLO : Detecção de\nsemáforos de\npedestres
    YOLO --> TDETECT : Classe e confiança\npara cada objeto\ndetectado
    deactivate YOLO

    hnote over TDETECT : Trata as detecções e\ndecide entre **STOP** e **GO**


    TDETECT -> MT ++: Estado Inferido
    & MT -> TAUD ++: Estado Inferido

    MT -> MT: Atualiza\nfeedback\ntátil (PWM)
    & TAUD -> TAUD : Atualiza\nfeedback\nauditivo
    & TDETECT -> TDETECT : Atualizada\ndados da\nsessão

    MT --> USER: Vibração
    TAUD --> USER: Comando verbal
    TDETECT -> TDETECT : Salva imagem com\nbounding boxes

    USER -> CTRLS : Pressiona\no botão
    CTRLS -> TDETECT: Encerra sessão
end

TDETECT -> TDETECT : Salva relatório\nda sessão

TDETECT -> MT !!: Desativa o motor
TDETECT -> TAUD !!: Encerra thread
CTRLS -> TDETECT !!: Encerra thread

@enduml